### ISSUE TITLE
duplicated option: s2s_use_starttls

### ISSUE THREAD

**Issue by GoliathLabs** [ThomasLeister/trashserver.net-xmpp#1]
`2019-12-22 13:05:36.319 [critical] <0.115.0>@ejabberd_app:start:71 Failed to start ejabberd application: Configuration error: duplicated option: s2s_use_starttls`
Can be resolved by removing one of both options

EDIT.: You might also add tlsv1.3 to the nginx tls config
Cheers

**Comment by licaon-kter** [comment]
@GoliathLabs umm you see this or what?

**Comment by GoliathLabs** [comment]
Yes. ejabberd's error log

**Comment by GoliathLabs** [comment]
@licaon-kter or what do you mean by that?

**Comment by licaon-kter** [comment]
@GoliathLabs so why report it here instead of ejabberd?

**Comment by GoliathLabs** [comment]
Because the options is duplicate in the config provided here. It's not a problem of ejabberd

**Comment by GoliathLabs** [comment]
Fixed in the last few commits. Closing...
